### ISSUE TITLE
Catching connectivity error

### ISSUE THREAD

**Issue by lucastsantos** [zino-app/graphql-flutter#105]
**Is your feature request related to a problem? Please describe.**
Currently, whenever there's an error related to user-server connectivity, an exception is thrown. Using the Query Widget, the initial call with loading=true is the only call received.

**Describe the solution you'd like**
I would like to be able to catch these connectivity errors and display an error in the UI

**Describe alternatives you've considered**
The stacktrace of the exception is not something that can be catched in the Query widget.
I've searched docs and issues for this use case. Looked in the Query widget but didn't found a way to achieve this. (Correct me if i'm wrong 😄). 

**Additional context**
I'm using version `^1.0.0-alpha.7`

Stacktrace (Android):
```
E/flutter (19711): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (19711): SocketException: Failed host lookup: '##ommited##' (OS Error: No address associated with hostname, errno = 7)
E/flutter (19711): #0      QueryManager.fetchQuery (package:graphql_flutter/src/core/query_manager.dart:113:19)
E/flutter (19711): <asynchronous suspension>
E/flutter (19711): #1      QueryScheduler.sheduleQuery.<anonymous closure> (package:graphql_flutter/src/scheduler/scheduler.dart:72:22)
E/flutter (19711): #2      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (19711): #3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (19711): #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (19711): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Steps to reproduce:
Disable connection of the device and run a query

**Comment by HofmannZ** [comment]
Proposed a fix in PR #107.
