### ISSUE TITLE
Use sdk version constraints to better manage api changes

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#477]
## Problem
We had an issue where `dart:ui` changed the `AppLifecycleState` api, breaking our library. The way we discovered this was through an issue, and because of our lack of metadata around compatible sdk versions, we were forced to overly generalize with #475

## Solution
This will take a little investigation, but will probably look something like
- [ ] better constrain version number
- [ ] implement some maintainer process for testing new sdk releases (dart lang, ui, flutter)

**Comment by lookfirst** [comment]
```
    Compiler message:
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.1-beta.3/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
          case AppLifecycleState.suspending:
                                 ^^^^^^^^^^
    Exception: Errors during snapshot creation: null
    #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:231:7)
    <asynchronous suspension>
    #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
```

**Comment by lookfirst** [comment]
Next version doesn't seem to be on pub yet.

**Comment by lookfirst** [comment]
`The latest dev release was 2.1.1-beta.3 on Nov 13, 2019.`

**Comment by lookfirst** [comment]
@micimize Hey! Please update pub.

**Comment by lookfirst** [comment]
This has been done. Thanks!

**Comment by micimize** [comment]
@lookfirst please don't spam threads with effectively the same comment over and over, on this or other projects. No FOSS maintainer owes you their time. You could have just used a [git dependency](https://dart.dev/tools/pub/dependencies#git-packages) to work around this.

**Comment by micimize** [comment]
A follow up comment after a few weeks of inactivity would have been appropriate in this case

**Comment by lookfirst** [comment]
I wasn't expecting your time. I was trying to let others know to not waste their time trying to figure out what was wrong when their compile suddenly broke and hopefully notify you that you forgot to push the release to pub. Notice the thumbs up above?

A little advice from someone who's been doing OSS for over 25 years now? Chill out on getting upset... that is the only thing not worth your energy. It is just a message on a wall, not spam.

**Comment by micimize** [comment]
@lookfirst just trying to promoting good OS etiquette. I guess we have different philosophies on what that constitutes.
