### ISSUE TITLE
Upload martipartFile mutation with cache error

### ISSUE THREAD

**Issue by Goxiaoy** [zino-app/graphql-flutter#724]
**Describe the issue**
If user create  a mutation besides FetchPolicy.noCache, cache normalizer will throw exception

**Expected behavior**
Always prevent cache in a martipartFile mutation 

**device / execution context**
Any

### Other useful/optional fields

<details>
  <summary>Stacktrace:</summary>

```dart
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _defaultToEncodable (dart:convert/json.dart:521:55)
#2      _JsonStringifier.writeObject (dart:convert/json.dart:681:36)
#3      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#4      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#5      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#6      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
#7      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
#8      JsonEncoder.convert (dart:convert/json.dart:261:30)
#9      JsonCodec.encode (dart:convert/json.dart:171:45)
#10     fieldNameWithArguments (package:normalize/src/utils/field_name_with_arguments.dart:64:27)
#11     denormalize.denormalizeNode.<anonymous closure> (package:normalize/src/denormalize.dart:101:29)
#12     ListMixin.fold (dart:collection/list.dart:218:22)
#13     denormalize.denormalizeNode (package:normalize/src/denormalize.dart:98:31)
#14     denormalize (package:normalize/src/denormalize.dart:128:27)
#15     NormalizingDataProxy.readQuery (package:graphql/src/cache/_normalizing_data_proxy.dart:60:7)
#16     QueryManager._resolveQueryOnNetwork (package:graphql/src/core/query_manager.dart:197:32)
<asynchronous suspension>
#17     QueryManager.fetchQueryAsMultiSourceResult (package:graphql/src/core/query_manager.dart:152:17)
#18     QueryManager.fetchQuery (package:graphql/src/core/query_manager.dart:126:9)
#19     QueryManager.mutate (package:graphql/src/core/query_manager.dart:99:12)
#20     GraphQLClient.mutate (package:graphql/src/graphql_client.dart:141:25)
#21     UploadRepo._uploadFile (package:FastBraiin/repository/upload_repo.dart:40:30)
<asynchronous suspension>
```

</details>

If you want to troubleshoot or discuss in real time, consider coming to the `support` channel in the [discord](https://discord.gg/tXTtBfC)

**Comment by vasilich6107** [comment]
This is a duplicated issue.
Could you close this one in favour of #723

**Comment by Goxiaoy** [comment]
Sorry, have not noticed with that.
