### ISSUE TITLE
Maybe Not sending Subscription to Server 

### ISSUE THREAD

**Issue by freewebwithme** [zino-app/graphql-flutter#757]
I am creating GraphQLClient like this.

```
  GraphQLClient graphQLClient() {
    final httpLink = HttpLink(httpEndpoint);
    final wsLink = WebSocketLink(
      wsEndpoint,
      config: SocketClientConfig(
        initialPayload: () {
          return {"token": token};
        },
        autoReconnect: true,
        inactivityTimeout: Duration(seconds: 30),
      ),
    );

    final authLink = AuthLink(getToken: () async => 'Bearer $token');
    final Link link = authLink.concat(httpLink);

    /// Subscriptions must be split otherwise 'HttpLink' wil swallow them.
    final splitLink =
        Link.split((request) => request.isSubscription, wsLink, link);

    return GraphQLClient(cache: GraphQLCache(), link: splitLink);
  }
```
and api.dart file

```
  Stream<QueryResult> subscribeToCartChange() {
    var subscription = _client.subscribe(
      SubscriptionOptions(
        document: gql(cartChange),
        operationName: "cartChange",
        variables: {"userId": session.user.id},
      ),
    );
    return subscription;
  }
```

in bloc file

```
  @override
  Stream<SubscribeToCartState> mapEventToState(
    SubscribeToCartEvent event,
  ) async* {
    if (event is SubscribeToCartChange) {

      var subscription = checkoutApi.subscribeToCartChange();
      _cartChangeSubscription = subscription.listen((result) async* {
      if (result.hasException) {
        print("Error from cartChange ${result.exception}");
         yield SubscribeToCartInitial();
      }
      if (result.isLoading) {
        print("Loading cartChange");
        yield SubscribeToCartInitial();
      }
        var carts = Carts.fromJson(result.data["cartChange"]);
        yield SubscribeToCartUpdated(carts: carts);
      });
    }
  }

```
While executing this, I got a error on `subscription.listen` function says

```
E/flutter ( 9645): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'value' was called on null.
E/flutter ( 9645): Receiver: null
E/flutter ( 9645): Tried calling: value
E/flutter ( 9645): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5))
E/flutter ( 9645): #1      getOperationDefinition.<anonymous closure> 
package:normalize/…/utils/get_operation_definition.dart:10
E/flutter ( 9645): #2      Iterable.firstWhere  (dart:core/iterable.dart:575:15))
E/flutter ( 9645): #3      getOperationDefinition 
package:normalize/…/utils/get_operation_definition.dart:9
E/flutter ( 9645): #4      denormalizeOperation 
package:normalize/src/denormalize_operation.dart:42
E/flutter ( 9645): #5      NormalizingDataProxy.readQuery 
package:graphql/…/cache/_normalizing_data_proxy.dart:67
E/flutter ( 9645): #6      QueryManager.subscribe 
```

And there is not reaction about subscription.
I think my client doesn't trigger a subscription to server.
What am I missing?

How can I check if I am sending request using ws link?

**Comment by micimize** [comment]
As this is coming from `get_operation_definition.dart`, I'm guessing there is not an operation named `"cartChange"`. What is the definition of `cartChange`?

**Comment by freewebwithme** [comment]
Maybe I am using it incorrectly?
It is from gql(cartChange).
```
String cartChange = """
subscription {
  cartChange {
   .....
  }
}
"""';

```

**Comment by micimize** [comment]
@freewebwithme right – for this subscription you can either skip `operationName` (it is only necessary when there are multiple operations in the same string) or write something like:
```dart
String cartChange = """
subscription cartChange {
  cartChange {
   .....
  }
}
"""';
```

**Comment by freewebwithme** [comment]
@micimize I will try!
Quick question, Do I have to use SocketClient for web socket connection? or just GraphQLClient is enough

**Comment by micimize** [comment]
@freewebwithme `WebSocketLink` creates a `SocketClient` itself

**Comment by freewebwithme** [comment]
@micimize 
After removing operationName it sends a subscription to the server. but I got this error

```
I/flutter ( 6268): Connecting to websocket: ws://192.168.1.11:4000/socket...
I/flutter ( 6268): There was an error causing connection lost: WebSocketException: Connection to 'http://192.168.1.11:4000/socket#' was not upgraded to websocket
I/flutter ( 6268): Disconnected from websocket.
```

I am using Phoenix framework using Absinthe graphql for backend server.
And I got an error in backend server that says "no route for GET /socket"
I don't know if I need a extra packages like [this](https://pub.dev/packages/absinthe_socket) and [this](https://pub.dev/packages/phoenix_wings) for my server.

Do you have any idea?

**Comment by micimize** [comment]
@freewebwithme haven't used it, but yeah you probably need to add a websocket lib

**Comment by freewebwithme** [comment]
@micimize Thanks. I will try!
