### ISSUE TITLE
graphql Subscription issue on cloud

### ISSUE THREAD

**Issue by brianschardt** [zino-app/graphql-flutter#811]
**Describe the issue**
When I try to use a subscription it goes in an infinite loop between connect and disconnect, and as a result, does not work on cloud environment. 
What is weird is it works against my local backend but not my cloud gcp cloud run api. However, I have tested my cloud backend api with other graphql subscription clients and it works perfectly. So I know my backend is not the issue. 

**Expected behavior**
Stay connected

**device / execution context**
IOS Simulator

### Other useful/optional fields

**screenshots**

**additional context**
Graphql, Apollo Server, NestJs

**Comment by micimize** [comment]
To quote myself from an [earlier issue](https://github.com/zino-app/graphql-flutter/issues/361#issuecomment-704960852):
> the websocket link automatically disconnects on inactivity timeout, and reconnects if the autoreconnect config is set. See discussion in #653 for more info
> 
> ```dart
> SocketClientConfig(
>   autoReconnect: true, // false to disable reconnect
>   inactivityTimeout: Duration(seconds: 30), // set to 0 to disable timeout
> )
> ```

Do actual `client.subscribe` or `Subscription` calls yield any results? If there is an issue I'll need some actual code to diagnose it

**Comment by brianschardt** [comment]
Here is a quick short code test project that shows my issue

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:graphql/client.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  init() {
    WebSocketLink wsLink =
        WebSocketLink('wss://api.dev.iris.finance/subscription',
            config: SocketClientConfig(
              autoReconnect: true, // false to disable reconnect
              inactivityTimeout:
                  Duration(seconds: 0), // set to 0 to disable timeout
            ));
    GraphQLClient client = GraphQLClient(
      cache: GraphQLCache(),
      link: wsLink,
    );

    final subscriptionDocument = gql(
      r'''
subscription {
  collectionAddedText(input: {collectionKey: 1}) {
    text {
      textKey
      createdAt
      orderedCreatedAt
      value
    }
  }
}
  ''',
    );

    var s = client.subscribe(
      SubscriptionOptions(document: subscriptionDocument),
    );
    s.listen((d) {
      print('RECEIVED');
    });
  }

  @override
  Widget build(BuildContext context) {
    init();
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Container(
        color: Colors.blue,
      ),
    );
  }
}
```

**Comment by brianschardt** [comment]
Also to note it connects and then disconnects immediately.
I have played around with changing these values 
```
inactivityTimeout:
                  Duration(seconds: 0), // set to 0 to disable timeout
```

**Comment by Setti7** [comment]
Cloud run had problems with websockets in the past, maybe its a problem on their end?

**Comment by micimize** [comment]
My guess is that this has something to do with their authentication scheme. 

> However, I have tested my cloud backend api with other graphql subscription clients and it works perfectly

If you provide all the details of networks requests made by the other clients (headers, etc) we can probably figure it out. May have to use a [header-enabled websocket link](https://gist.github.com/micimize/04ee011b445d38ce34193a5225992504)

**Comment by brianschardt** [comment]
I got the headers from nodejs client code that works:
```
GET /subscription HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: LchF/g+2UX0Z3X86VobTyg==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: graphql-ws
```

Here is nodejs client code.  
```
const WebSocket = require('ws');

let wsUrl = 'wss://api.dev.iris.finance/subscription';

const ws = new WebSocket(wsUrl, ['graphql-ws']);
let message = '{"id":"1","type":"start","payload":{"variables":{},"extensions":{},"operationName":null,"query":"subscription {  collectionAddedText(input: {collectionKey: 4}) {    text {      textKey      value    }  }}"}}'

ws.on('open', function open() {
  console.log('Open; sending message');
  ws.send(message);
});

ws.on('message', function incoming(data) {
  console.log('Receive data');
  console.log(data);
});

ws.on('close', function close(d) {
  console.log('disconnected d', d);
});


```

**Comment by brianschardt** [comment]
I think this is completely separate from this graphql package and think this is a flutter/dart issue.

**Comment by micimize** [comment]
@brianschardt I tried both your dart code and node code, given that. The dart code (simplified with some logging) disconnects with a `1005`, "No Status Received" while the node code just hangs after sending a message.

I highly doubt there is an issue with dart or the underlying websocket implementation. 
```dart
import 'package:graphql/client.dart';

void main() {
  final wsLink = WebSocketLink(
    'wss://api.dev.iris.finance/subscription',
    config: SocketClientConfig(
      autoReconnect: true, // false to disable reconnect
      // 0 second inactivityTimeout doesn't disable it
      inactivityTimeout: const Duration(seconds: 30),
      onConnectOrReconnect: (ws) => ws.stream.listen(
        (event) {
          print(['data', event]);
        },
        onError: (event) {
          print(['error', event]);
        },
        onDone: () {
          print(['done', ws.closeCode, ws.closeReason]);
        },
      ),
    ),
  );
  final client = GraphQLClient(
    cache: GraphQLCache(),
    link: wsLink,
  );

  final subscriptionDocument = gql(
    r'''
subscription {
  collectionAddedText(input: {collectionKey: 4}) {
    text {
      textKey
      createdAt
      orderedCreatedAt
      value
    }
  }
}
  ''',
  );

  var s = client.subscribe(
    SubscriptionOptions(document: subscriptionDocument),
  );
  s.listen((d) {
    print('RECEIVED');
  });
}
```

**Comment by brianschardt** [comment]
@micimize Because this is a websocket hanging is expected, it is listening for data. We actually figured out the issue, its deep into the dart websocket http library. They automatically set content-length = 0 in the headers. Once we remove that it all works as expected.

**Comment by micimize** [comment]
right you are – we should integrate the workaround in https://github.com/dart-lang/sdk/issues/43574#issuecomment-761106329 into the library

**Comment by brianschardt** [comment]
@micimize i agree is this something that you can do easily? If not ill look into having my team implement it.

**Comment by micimize** [comment]
@brianschardt I am fairly busy these days, so I'd recommend PRing to `beta` if you want it merged urgently.

**Comment by thomas-ferchau** [comment]
@aam, thank you very much for looking into this.
@brianschardt @slightfoot, thank you for pointing to the `content-length` header.

I suggest a modification to `websocket_impl.dart` if changing `http_impl.dart` is too wide-ranging. The proposed change can be seen here:
https://github.com/dart-lang/sdk/issues/45139#issuecomment-828344653

With this change, HTTPS/WSS works for me:
````
dart run wsclient.dart --url wss://websocket-echo-server-quarkus-xxxxxxxxxx-xx.x.run.app/websocket
dart run wsclient.dart --url wss://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/
````

But HTTP/WS does not work even with the `content-length` header removed:
````
dart run wsclient.dart --url ws://websocket-echo-server-quarkus-xxxxxxxxxx-xx.x.run.app/websocket
dart run wsclient.dart --url ws://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/
````

There is an interesting log output from the Python echo server:
````
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
````

You can easily start my little Python WebSocket echo server on Google Cloud Run here to try that:
https://github.com/buehren/websocket-echo-server-python#server-cloudrun


**As the problem starts in `websockets/framing.py`, maybe there is something wrong with the frame header?**
This seems to be a separate problem. Could it have something to do with the redirect from HTTP to HTTPS?
You can see the exact line here:
https://github.com/aaugustin/websockets/blob/8.1/src/websockets/framing.py#L105


This is the complete log output:
````
2021-04-28 12:36:09.115 CEST GET 302 0 B 0 ms Dart/2.12 (dart:io) http://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/
2021-04-28 12:36:11.600 CEST GET 101 483 B 2.2 s Dart/2.12 (dart:io) https://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/
2021-04-28 12:36:11.601 CEST Error in connection handler
2021-04-28 12:36:11.601 CEST Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data message = await self.read_message() File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message frame = await self.read_data_frame(max_size=self.max_size) File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame frame = await self.read_frame(max_size) File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame frame = await Frame.read( File "/usr/local/lib/python3.8/site-packages/websockets/framing.py", line 105, in read data = await reader(2) File "/usr/local/lib/python3.8/asyncio/streams.py", line 721, in readexactly raise exceptions.IncompleteReadError(incomplete, n) asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
2021-04-28 12:36:11.601 CEST
2021-04-28 12:36:11.601 CEST The above exception was the direct cause of the following exception:
2021-04-28 12:36:11.601 CEST
2021-04-28 12:36:11.601 CEST Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 191, in handler await self.ws_handler(self, path) File "wsecho.py", line 8, in echo async for message in websocket: File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__ yield await self.recv() File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv await self.ensure_open() File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open raise self.connection_closed_exc() websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
````

It was produced for this run:
````
> dart run wsclient.dart --url ws://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/
2021-04-28 10:36:08.927888 Starting connection attempt to ws://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/ ...
2021-04-28 10:36:09.483541 WebSocket readyState: 1
2021-04-28 10:36:11.517937 Sending 'hello'
2021-04-28 10:36:11.679346 CONNECTION DONE!
readyState=3
closeCode=1005
closeReason=

2021-04-28 10:36:13.486038 Sending 'how are you?'
2021-04-28 10:36:15.485670 Sending 'still there?'
````


Maybe a tcpdump would help to investigate the problem (created from another run):
````
> sudo tcpdump -vv -i any port 80

tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
10:59:55.292569 IP (tos 0x0, ttl 64, id 48126, offset 0, flags [DF], proto TCP (6), length 60)
    10.0.2.15.57920 > 216.239.36.53.http: Flags [S], cksum 0x0962 (incorrect -> 0xd9ac), seq 4123479103, win 64240, options [mss 1460,sackOK,TS val 3505091755 ecr 0,nop,wscale 7], length 0
10:59:55.325695 IP (tos 0x0, ttl 64, id 54339, offset 0, flags [none], proto TCP (6), length 44)
    216.239.36.53.http > 10.0.2.15.57920: Flags [S.], cksum 0x411e (correct), seq 1193992705, ack 4123479104, win 65535, options [mss 1460], length 0
10:59:55.325729 IP (tos 0x0, ttl 64, id 48127, offset 0, flags [DF], proto TCP (6), length 40)
    10.0.2.15.57920 > 216.239.36.53.http: Flags [.], cksum 0x094e (incorrect -> 0x5dea), seq 1, ack 1, win 64240, length 0
10:59:55.363573 IP (tos 0x0, ttl 64, id 48128, offset 0, flags [DF], proto TCP (6), length 382)
    10.0.2.15.57920 > 216.239.36.53.http: Flags [P.], cksum 0x0aa4 (incorrect -> 0x6a45), seq 1:343, ack 1, win 64240, length 342: HTTP, length: 342
        GET / HTTP/1.1
        user-agent: Dart/2.12 (dart:io)
        connection: Upgrade
        cache-control: no-cache
        accept-encoding: gzip
        sec-websocket-version: 13
        host: websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app
        sec-websocket-extensions: permessage-deflate; client_max_window_bits
        sec-websocket-key: 67fEJW101wAwI7lzopzgLQ==
        upgrade: websocket

10:59:55.363712 IP (tos 0x0, ttl 64, id 54340, offset 0, flags [none], proto TCP (6), length 40)
    216.239.36.53.http > 10.0.2.15.57920: Flags [.], cksum 0x5785 (correct), seq 1, ack 343, win 65535, length 0
10:59:55.639752 IP (tos 0x0, ttl 64, id 54341, offset 0, flags [none], proto TCP (6), length 368)
    216.239.36.53.http > 10.0.2.15.57920: Flags [P.], cksum 0xec55 (correct), seq 1:329, ack 343, win 65535, length 328: HTTP, length: 328
        HTTP/1.1 302 Found
        location: https://websocket-echo-server-python-xxxxxxxxxx-xx.x.run.app/
        x-cloud-trace-context: 474229585e7cad4832ea12b1422165bb
        date: Wed, 28 Apr 2021 10:59:55 GMT
        server: Google Frontend
        x-envoy-upstream-service-time: 134
        Content-Length: 0
        Content-Type: text/html; charset=UTF-8
        Connection: close

10:59:55.639780 IP (tos 0x0, ttl 64, id 48129, offset 0, flags [DF], proto TCP (6), length 40)
    10.0.2.15.57920 > 216.239.36.53.http: Flags [.], cksum 0x094e (incorrect -> 0x5c94), seq 343, ack 329, win 63912, length 0

````

**Comment by thomas-ferchau** [comment]
I suggest a modification to `websocket_impl.dart` if changing `http_impl.dart` is too wide-ranging. 
The proposed change can be seen here:
https://github.com/dart-lang/sdk/issues/45139#issuecomment-828344653

There seems to be another problem in case of a redirect from HTTP to HTTPS and then upgrading to WSS:
https://github.com/dart-lang/sdk/issues/43574#issuecomment-828366042

**Comment by micimize** [comment]
Hi @hschk — I haven't been a maintainer of this project for some time, but if things haven't changed dramatically you can probably go into the gql link middleware for subscriptions and patch the header issue. 

The architecture doc should help point you in the right direction
