### ISSUE TITLE
Using Mutation throws exception

### ISSUE THREAD

**Issue by lordgreg** [zino-app/graphql-flutter#83]
**Describe the bug**

When user clicks on button, the mutation should be sent. However, button isn't even shown. The error appears.

Keep in mind, I do not get any lint errors.

```
I/flutter (12453): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12453): The following assertion was thrown building Mutation(dirty, state: MutationState#ebddc):
I/flutter (12453): type '(Map<String, dynamic>) => void' is not a subtype of type '(Map<String, dynamic>) =>
I/flutter (12453): Future<void>'
I/flutter (12453):
I/flutter (12453): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12453): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12453): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12453):   https://github.com/flutter/flutter/issues/new
I/flutter (12453):
I/flutter (12453): When the exception was thrown, this was the stack:
I/flutter (12453): #0      MutationState.build (package:graphql_flutter/src/widgets/mutation.dart:80:7)
I/flutter (12453): #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (12453): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (12453): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12453): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (12453): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (12453): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (12453): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (12453): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (12453): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (12453): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (12453): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (12453): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (12453): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (12453): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
```

**To Reproduce**
```
                new Container(
                  padding: EdgeInsets.all(ThemeSettings.PADDING_DEFAULT / 2),
                  height: 60.0,
                  width: double.infinity,
                  child: new Mutation(
                    GraphQl.setMarketTariff(Data.tariffData),
                    builder: (
                      foo, {
                      bool loading,
                      var data,
                      Exception error,
                    }) {
                      return new FlatButton(
                        color: Colors.white,
                        disabledColor: Theme.of(context).disabledColor,
                        onPressed: _tabController.index == _usedTariff
                            ? null
                            : () {
                                foo({
                                  'foo': 'bar'
                                });
                              },
                        child: new Text(
                          DemoLocalizations.of(context)
                              .get(_tabController.index == _usedTariff
                                  ? 'TARIFF.SELECTED'
                                  : 'TARIFF.USE')
                              .toUpperCase(),
                          style: new TextStyle(
                              color: _tabController.index == _usedTariff
                                  ? Colors.white
                                  : Colors.black,
                              fontSize: 18.0),
                        ),
                      );
                    },
                    onCompleted: (Map<String, dynamic> data) {
                      print("COMPLETED $data");
                    },
                  ),
                )
```

**Expected behavior**
Show button properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/480546/45037753-f7c40300-b05f-11e8-81bf-25ad329b6708.png)

Without mutation, the FlatButton should show.

```
▶ flutter --version
Flutter 0.6.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 9299c02cf7 (3 weeks ago) • 2018-08-16 00:35:12 +0200
Engine • revision e3687f70c7
Tools • Dart 2.1.0-dev.0.0.flutter-be6309690f

graphql-flutter version in pubspec.yaml:  graphql_flutter: ^0.9.1
```

Also, it would be good to provide the same functionality as with queries where I can simply call:
```
    Client client = GraphQl.client.value;
    client
        .query(query: GraphQl.getTariffInformation())
```

So that we could call:
```
    Client client = GraphQl.client.value;
    client
        .mutation(mutation: GraphQl.setTariffInformation())

```

**Comment by HofmannZ** [comment]
Thanks for the issue report.
Should be fixed by #84

**Comment by HofmannZ** [comment]
@lordgreg Could you provide me with a review on that commit, so I can start shipping ;)

**Comment by lordgreg** [comment]
I sure can but sadly not before tomorrow morning (in 14 hours). Will this be suitable for you?

**Comment by HofmannZ** [comment]
@lordgreg Tomorrow is fine, once I have a review I can merge and you can have the bug fixed.

Also it might be interesting to have a look at version `1.0.0-alpha.4` where many of these bugs are already solved. ✌🏻

**Comment by lordgreg** [comment]
Hi @HofmannZ- I've just tried your #84.

However, as someone already mentioned in post here (https://github.com/zino-app/graphql-flutter/issues/77), onComplete doesn't execute. 

But for the issue I was having, I can confirm its now working as it should. 👍
