### ISSUE TITLE
Can't initialise Hive store

### ISSUE THREAD

**Issue by zhaoyi0113** [zino-app/graphql-flutter#874]
I am using the code from the readme but got below error when run `flutter run`:
```
or a more detailed help message, press "h". To quit, press "q".
Error: HiveError: Box not found. Did you forget to call Hive.openBox()?
    at Object.throw_ [as throw] (http://localhost:58299/dart_sdk.js:5333:11)
    at hive_impl.HiveImpl.new.[_getBoxInternal]
    (http://localhost:58299/packages/hive/src/box/lazy_box_impl.dart.lib.js:3013:19)
    at hive_impl.HiveImpl.new.box
    (http://localhost:58299/packages/hive/src/box/lazy_box_impl.dart.lib.js:3021:77)
    at new hive_store.HiveStore.new
    (http://localhost:58299/packages/graphql/src/cache/hive_store.dart.lib.js:72:52)
    at main$ (http://localhost:58299/packages/app/main.dart.lib.js:725:156)
    at main$.next (<anonymous>)
    at runBody (http://localhost:58299/dart_sdk.js:39051:34)
    at Object._async [as async] (http://localhost:58299/dart_sdk.js:39082:7)
    at main$ (http://localhost:58299/packages/app/main.dart.lib.js:721:18)
    at main (http://localhost:58299/web_entrypoint.dart.lib.js:49:29)
    at main.next (<anonymous>)
    at http://localhost:58299/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:58299/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:58299/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:58299/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:58299/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:58299/dart_sdk.js:34314:23)
    at http://localhost:58299/dart_sdk.js:33525:46
    at _RootZone.runUnary (http://localhost:58299/dart_sdk.js:38888:58)
    at _FutureListener.then.handleValue (http://localhost:58299/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:58299/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:58299/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:58299/dart_sdk.js:34314:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58299/dart_sdk.js:34337:35)
    at Object._microtaskLoop (http://localhost:58299/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:58299/dart_sdk.js:39181:13)
    at http://localhost:58299/dart_sdk.js:34688:9
```

Below is the complete code.  What should I do to fix the error?

```
import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';

var httpLink = HttpLink(
  'https://api.github.com/graphql',
);

var authLink = AuthLink(
  getToken: () => 'Bearer <YOUR_PERSONAL_ACCESS_TOKEN>',
);

final Link link = authLink.concat(httpLink);

ValueNotifier<GraphQLClient> client = ValueNotifier(
  GraphQLClient(
    link: link,
    // The default store is the InMemoryStore, which does NOT persist to disk
    cache: GraphQLCache(store: HiveStore()),
  ),
);

final provider = GraphQLProvider(
  client: client,
  child: MaterialApp(
    title: 'CRMS',
  ),
);

```

**Comment by lohitbura** [comment]
I am also facing the same issue . Please provide a solution

**Comment by lohitbura** [comment]
@zhaoyi0113  I solved this issue by adding following line in my main function

await initHiveForFlutter();

**Comment by silasrm** [comment]
I'm has this init function but when call a Mutation, return: HiveError: Box not found. Did you forget to call Hive.openBox()?

**Comment by Achudh** [comment]
> @zhaoyi0113 I solved this issue by adding following line in my main function
> 
> await initHiveForFlutter();

Thank you so much, it worked

**Comment by zhaoyi0113** [comment]
It works by @lohitbura 's solution

**Comment by the-best-is-best** [comment]
initHiveForFlutter();
not found

**Comment by vincenzopalazzo** [comment]
Can you add a little bit more content here? @the-best-is-best

**Comment by Achudh** [comment]
> initHiveForFlutter(); not found

Seems like there is an issue with importing the package. @the-best-is-best try 
```flutter clean``` and  ```flutter pub get``` and import the package with ```import "package:graphql_flutter/graphql_flutter.dart";```
